config/routes.rb
Rails.application.routes.draw do

  resources :styles, only: [:index]
  resources :beers, only: [:index, :show]

  resources :styles, only: [:index], param: :slug do
    resources :beers, only: [:index]
  end

  resources :users, only: [:new, :create] do
    resources :orders, only: [:create, :show]
  end

  get '/orders', to: 'orders#index'

  get '/dashboard', to: 'dashboard#show'

  resources :cart, only: [:create]

  delete '/cart/remove', path: 'destroy/:id'
  post '/cart/update', path: 'update'
  get '/cart' => 'cart#show'

  get '/items' => 'beers#index'

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  root to: 'sessions#new'

  namespace :admin do
    get '/dashboard', to: 'dashboard#show'
    post '/dashboard/paid', to: 'dashboard#paid', as: 'order_paid'
    post '/dashboard/cancel', to: 'dashboard#cancel', as: 'order_cancel'
    post '/dashboard/complete', to: 'dashboard#complete', as: 'order_complete'

    resources :users, only: [:edit, :update]
    resources :beers, only: [:index, :edit, :update]
  end
  
  get '/:slug' => 'styles#show'

end

app/models/cart.rb
class Cart
  attr_reader :contents

  def initialize(initial_contents)
    @contents = initial_contents || {}
  end

  def add_beer(beer_id)
    contents[beer_id.to_s] ||= 0
    contents[beer_id.to_s] += 1
  end

  def total
    contents.values.sum
  end

  def count_of(beer_id)
    contents[beer_id.to_s]
  end

  def get_quantity_of_beer(beer)
    contents[beer.id.to_s]
  end

end

app/controllers/cart_controller.rb
class CartController < ApplicationController

  def create
    beer = Beer.find(params[:beer_id])
    @cart.add_beer(beer.id)
    session[:cart] = @cart.contents
    flash[:success] = "#{beer.name} added to cart!"
    redirect_to(:back)
  end

  def show
  end

  def index
  end

  def remove
    cart = session[:cart]
    cart.delete(params[:id])
    beer = Beer.find(params[:id])
    flash[:success] = %Q[Successfully removed <a href="/beers/#{beer.id}">#{beer.name}</a> from cart!].html_safe
    redirect_to cart_path
  end

  def destroy
  end

  def update
    @cart.contents[params[:beer]] = params[:quantity].to_i
    redirect_to cart_path
  end


end

app/views/cart/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Your Cart</div>
  <table class="table">
  <tr>
    <th></th>
    <th>Beer</th>
    <th>Quantity</th>
    <th></th>
    <th>Price</th>
    <th>Subtotal</th>
  </tr>
  <% cart_beers.each do |beer| %>
  <tr>
    <td><%= image_tag(beer.image.url, :height => '25', :width => '40') %></td>
    <td><%= beer.name %></td>
    <td><%= @cart.contents[beer.id.to_s] %></td>
    <td><span class="glyphicon glyphicon-align-left" aria-label="Left Align" data-toggle="tooltip" data-placement="top" title="<%= beer.description %>"></span></td>
   <td><%= number_to_currency(beer.price) %></td>
   <td><%= cart_row_subtotal(beer) %></td>
   <td><%= form_tag cart_update_path(:beer => beer.id) do %>
    <%= select_tag :quantity, options_for_select((0..99)) %>
   <%= submit_tag "Update" %></td>
      <% end %>
    <td><%= button_to "Remove", cart_remove_path(beer.id), method: :delete  %></td>
  <% end %>
    </tr>
  </table>
    <td><div class="cart-total">Total: <%= number_to_currency(cart_total) %></td></div>
  </div>
    <td><% if logged_in? %>
      <%= button_to "Checkout", user_orders_path(current_user), disabled: disable_place_order_button, class:"btn btn-secondary" %>
    <% end %>
    <% if logged_in?.nil? %>
      <p> To checkout, <%= link_to "Log In", login_path %> or <%= link_to "Create Account", new_user_path %> </p>
    <% end %></td>
</div>