config/routes.rb
Rails.application.routes.draw do

  resources :styles, only: [:index]
  resources :beers, only: [:index, :show]

  resources :styles, only: [:index], param: :slug do
    resources :beers, only: [:index]
  end

  resources :users, only: [:new, :create] do
    resources :orders, only: [:create, :show]
  end

  get '/orders', to: 'orders#index'

  get '/dashboard', to: 'dashboard#show'

  resources :cart, only: [:create]

  delete '/cart/remove', path: 'destroy/:id'
  post '/cart/update', path: 'update'
  get '/cart' => 'cart#show'

  get '/items' => 'beers#index'

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  root to: 'sessions#new'

  namespace :admin do
    get '/dashboard', to: 'dashboard#show'
    post '/dashboard/paid', to: 'dashboard#paid', as: 'order_paid'
    post '/dashboard/cancel', to: 'dashboard#cancel', as: 'order_cancel'
    post '/dashboard/complete', to: 'dashboard#complete', as: 'order_complete'

    resources :users, only: [:edit, :update]
    resources :beers, only: [:index, :edit, :update]
  end
  
  get '/:slug' => 'styles#show'

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
  include DashboardHelper

  def show
    set_order
  end

  def paid
    @order = Order.find(params[:order])
    @order.Paid!
    redirect_to admin_dashboard_path
  end


  def update
    @user = User.find(current_user.id)
  end

  def cancel
    @order = Order.find(params[:order])
    @order.Cancelled!
    redirect_to admin_dashboard_path
  end

  def complete
    @order = Order.find(params[:order])
    @order.Completed!
    redirect_to admin_dashboard_path
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def show
    @user = current_user
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper

  def set_order
    if params[:status] == "Ordered"
      @orders = Order.where(order_status: 0)
    elsif params[:status] == "Paid"
      @orders = Order.where(order_status: 1)
    elsif params[:status] == "Cancelled"
      @orders = Order.where(order_status: 2)
    elsif params[:status] == "Completed"
      @orders = Order.where(order_status: 3)
    else
      @orders = Order.all
    end
  end

end

app/views/admin/dashboard/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1>Admin Dashboard</h1>
    <div class="btn-group">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        Filter By Status <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu">
        <li><%= link_to "Ordered", admin_dashboard_path(status: "Ordered")%></li>
        <li><%= link_to "Paid", admin_dashboard_path(status: "Paid")%></li>
        <li><%= link_to "Cancelled", admin_dashboard_path(status: "Cancelled")%></li>
        <li><%= link_to "Completed", admin_dashboard_path(status: "Completed")%></li>
        <li class="divider"></li>
        <li><%= link_to "All", admin_dashboard_path %></li>
      </ul>
    </div>
  </div>

  <table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Customer Email</th>
      <th>Date Placed</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
    <tr>
      <td><%= link_to "#{order.id}", user_order_path(order.user, order) %></td>
      <td><%= order.user.email %></td>
      <td><%= order.format_created_by %></td>
      <td id="order_status"><%= order.order_status %></td>
      <% if order.order_status == "Paid" || order.order_status == "Ordered" %>
      <td>
          <%= button_to "Cancel", admin_order_cancel_path(order: order), class: "btn btn-danger"  %>
      </td>
      <% else %>
      <td>
          <%= button_to "Cancel", admin_order_cancel_path(order: order), disabled: true, class: "btn btn-danger"  %>
      </td>
    <% end %>
    <% if order.order_status == "Ordered" %>
    <td>
        <%= button_to "Mark As Paid", admin_order_paid_path(order: order), class: "btn btn-success" %>
    </td>
    <% else %>
    <td><%= button_to "Mark As Paid", admin_order_paid_path(order: order), disabled: true, class: "btn btn-success" %></td>
  <% end %>
  <% if order.order_status == "Paid" %>
  <td>
      <%= button_to "Mark As Completed", admin_order_complete_path(order: order), class: "btn btn-info"  %>
  </td>
  <% else %>
  <td>
    <%= button_to "Mark As Completed", admin_order_complete_path(order: order), disabled: true, class: "btn btn-info"  %>
</td>
<% end %>
  </tr>
    <% end %>
    <tr>
      <td> Total: <%= @orders.count %> </td>
      <td>
      </td>
      <td>
      </td>
      <td>
      </td>
    </tr>
  </tbody>
</table>
</div>
<br>
<div class="panel panel-default">
  <% if current_user %>
  <div class="panel-heading">
  <h4> Name: <%= current_user.first_name %> <%= current_user.last_name %></h4>
  </div>
  <h4> Email: <%= current_user.email %></h4>
  <h4> Address: <%= current_user.address %></h4>
  <%= link_to "Edit Admin User Info", edit_admin_user_path(@current_user), class: "btn btn-primary" %>
  <% end %>
</div>