config/routes.rb
Rails.application.routes.draw do

  resources :styles, only: [:index]
  resources :beers, only: [:index, :show]

  resources :styles, only: [:index], param: :slug do
    resources :beers, only: [:index]
  end

  resources :users, only: [:new, :create] do
    resources :orders, only: [:create, :show]
  end

  get '/orders', to: 'orders#index'

  get '/dashboard', to: 'dashboard#show'

  resources :cart, only: [:create]

  delete '/cart/remove', path: 'destroy/:id'
  post '/cart/update', path: 'update'
  get '/cart' => 'cart#show'

  get '/items' => 'beers#index'

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  root to: 'sessions#new'

  namespace :admin do
    get '/dashboard', to: 'dashboard#show'
    post '/dashboard/paid', to: 'dashboard#paid', as: 'order_paid'
    post '/dashboard/cancel', to: 'dashboard#cancel', as: 'order_cancel'
    post '/dashboard/complete', to: 'dashboard#complete', as: 'order_complete'

    resources :users, only: [:edit, :update]
    resources :beers, only: [:index, :edit, :update]
  end
  
  get '/:slug' => 'styles#show'

end

app/models/beer.rb
class Beer < ActiveRecord::Base
  belongs_to :style
  has_many :beer_orders
  has_many :orders, through: :beer_orders

  validates :name, presence: true, uniqueness: true
  validates :price, presence: true
  validates :style, presence: true

  has_attached_file :image, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  enum status: { instock: 0 , out_of_stock: 1 }

  def self.search(argument)
    if argument
      where("lower(name) LIKE ?", "%#{argument.downcase}%")
    else
      Beer.all
    end
  end


  def get_beer_order(order)
    beer_orders.find_by(order: order).quantity
  end

  def get_subtotal(order)
    price * get_beer_order(order)
  end

end

app/controllers/admin/beers_controller.rb
class Admin::BeersController < Admin::BaseController

  def index
    @beers = Beer.all
  end

  def edit
    @beer = Beer.find(params[:id])
    @styles = Style.all
  end

  def update
    @beer = Beer.find(params[:id])
    @beer.update(beer_params)
    if @beer.save
      flash[:success] = "#{@beer.name} updated!"
      redirect_to admin_beers_path
    else
      render :edit
    end
  end

  private

  def beer_params
    params.require(:beer).permit(:name, :price, :image, :style, :description, :status)

  end
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController

  def index
    @beers = Beer.search(params[:q])
  end

  def show
    @beer = Beer.find(params[:id])
  end

end

app/helpers/beers_helper.rb
module BeersHelper
  def cart_row_subtotal(beer)
    number_to_currency(@cart.contents[beer.id.to_s] * beer.price)
  end
end

app/views/admin/beers/edit.html.erb
<h2>Edit Your Beer</h2>

<%= form_for(@beer, multipart: true, url: admin_beer_path(@beer)) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :price %>
  <%= f.number_field :price %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.collection_select(:style_id, @styles, :id, :name) %>

  <%= f.label :image %>
  <%= f.file_field :image %>

  <%= f.label :out_of_stock? %>
  <%= f.check_box(:status, options = {}, checked_value = "out_of_stock", unchecked_value = "instock")%>

<%= f.submit %>
<% end %>

app/views/admin/beers/index.html.erb
<div class="row">
  <% @beers.each do |beer| %>
    <div class="col-sm-3">
      <div class="panel panel-default" id="panel_width">
        <div class="panel-heading text-center"><%= link_to beer.name, beer_path(beer) %> </div>
          <div class="panel-body text-center">
          <% if beer.status == "instock" %>
            <%= image_tag(beer.image.url(:square), :height => '180', :width => '240') %><br>
            <strong><%= number_to_currency(beer.price) %></strong><br>
            <span class="glyphicon glyphicon-align-left" aria-label="Left Align" data-toggle="tooltip" data-placement="top" title="<%= beer.description %>"></span>
            <div>
            <%= button_to "Add to Cart", cart_path(beer_id: beer.id), class: "btn btn-primary" %><%= link_to "Edit", edit_admin_beer_path(beer), class: "btn btn-primary" %>
            </div>
          <% else %>
          <div id="overlay">
            <div id="main_image"><%= image_tag(beer.image.url, :height => '180', :width => '240') %><br></div>
            <div id="overlay_image"><%= image_tag("sold-out-png-30.png", :height => '180', :width => '180') %><br></div>
          </div>
            <strong><%= number_to_currency(beer.price) %></strong><br>
            <span class="glyphicon glyphicon-align-left" aria-label="Left Align" data-toggle="tooltip" data-placement="top" title="<%= beer.description %>"></span>
            <%= button_to "Unavailable", cart_path(beer_id: beer.id), class: "btn btn-primary", disabled: true %>
            <%= link_to "Edit", edit_admin_beer_path(beer), class: "btn btn-primary" %>
        <% end %>

        </div>
      </div>
    </div>
  <% end %>
</div>