config/routes.rb
Rails.application.routes.draw do

  resources :styles, only: [:index]
  resources :beers, only: [:index, :show]

  resources :styles, only: [:index], param: :slug do
    resources :beers, only: [:index]
  end

  resources :users, only: [:new, :create] do
    resources :orders, only: [:create, :show]
  end

  get '/orders', to: 'orders#index'

  get '/dashboard', to: 'dashboard#show'

  resources :cart, only: [:create]

  delete '/cart/remove', path: 'destroy/:id'
  post '/cart/update', path: 'update'
  get '/cart' => 'cart#show'

  get '/items' => 'beers#index'

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  root to: 'sessions#new'

  namespace :admin do
    get '/dashboard', to: 'dashboard#show'
    post '/dashboard/paid', to: 'dashboard#paid', as: 'order_paid'
    post '/dashboard/cancel', to: 'dashboard#cancel', as: 'order_cancel'
    post '/dashboard/complete', to: 'dashboard#complete', as: 'order_complete'

    resources :users, only: [:edit, :update]
    resources :beers, only: [:index, :edit, :update]
  end
  
  get '/:slug' => 'styles#show'

end

app/views/layouts/_admin_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">iShopBeer</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Dashboard", admin_dashboard_path %></li>
        <li><%= link_to "All Beers", admin_beers_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Browse Styles<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All", styles_path %></li>
            <% @styles.each do |style| %>

                <li><a href="/<%= style.name.parameterize %>"><%= style.name %></a></li>

            <% end %>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <div class="navbar-form navbar-left">
          <%= form_tag(admin_beers_path, method: :get) do %>
          <div class="form-group">
            <%= label_tag :q %>
            <%= text_field_tag :q, nil, class: "form-control", placeholder: "Search Beers" %>
            <%= submit_tag "Search", class: "btn btn-default" %>
          </div>
        </div>
        <% end %>
        <li><a href="/cart/" id='cart'><span class="badge"><i class="glyphicon glyphicon-shopping-cart"></i> <%= get_total %></span></a></li>
      <% if logged_in? %>
        <li class="dropdown" id='login'>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Past Orders", admin_dashboard_path %></li>
            <li><%= link_to "Logout", logout_path, method: :delete %></li>
          </ul>
          <% else %>
          <li><%= link_to "Login", login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">iShopBeer</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Dashboard", dashboard_path %></li>
        <li><%= link_to "All Beers", beers_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Browse Styles<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All", styles_path %></li>
            <% @styles.each do |style| %>

                <li><a href="/<%= style.name.parameterize %>"><%= style.name %></a></li>

            <% end %>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <div class="navbar-form navbar-left">
          <%= form_tag(beers_path, method: :get) do %>
          <div class="form-group">
            <%= label_tag :q %>
            <%= text_field_tag :q, nil, class: "form-control", placeholder: "Search Beers" %>
            <%= submit_tag "Search", class: "btn btn-default" %>
          </div>
        </div>
        <% end %>
        <li><a href="/cart/" id='cart'><span class="badge"><i class="glyphicon glyphicon-shopping-cart"></i> <%= get_total %></span></a></li>
      <% if logged_in? %>
        <li class="dropdown" id='login'>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Past Orders", orders_path %></li>
            <li><%= link_to "Logout", logout_path, method: :delete %></li>
          </ul>
          <% else %>
          <li><%= link_to "Login", login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
    <head>
      <title>iShopBeer</title>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
      <!-- Latest compiled and minified CSS -->

      <!-- Optional theme -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </head>
    <body class="<%= params[:controller]%>">
      <% if current_admin? %>
        <%= render partial: "layouts/admin_navbar" %>
      <% else %>
        <%= render partial: "layouts/navbar" %>
      <% end %>
      <div class="container">
        <div class="container-fluid">
          <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %> alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <%= sanitize(value) %>
            </div>
        <% end %>
      </div>
      <%= yield %>

    </body>
    <div>
  </html>
</div>

app/views/layouts/error.html.erb
<h1>Party foul!</h1>